jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: dotnet build ZwaveExperiments.sln
    displayName: Build
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: dotnet build ZwaveExperiments.sln
    displayName: Build
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1